resolve helm chart location using registry mappings configured in the CloudBees platform

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -59,11 +59,13 @@ runs:
       run: |
         set -uo pipefail
 
+        resolved_registries="/tmp/resolved_registries.out"
+
         if echo "${CHART_LOCATION}" | grep -q '^oci://'; then
           if [ "${CLOUDBEES_REGISTRIES_CONFIG}" ]; then
             chart_location=$(echo -n "${CHART_LOCATION}" | sed 's|^oci://||')
-            registry-config --config "${CLOUDBEES_REGISTRIES_CONFIG}" resolve "${chart_location}" resolved_registries.out
-            echo "Resolved registries: $(cat resolved_registries.out)"
+            registry-config --config "${CLOUDBEES_REGISTRIES_CONFIG}" resolve "${chart_location}" ${resolved_registries}
+            echo "Resolved registries: $(cat ${resolved_registries})"
           fi
         fi
 
@@ -130,29 +132,24 @@ runs:
           | .deploy.statusCheckDeadlineSeconds = env(TIMEOUT_SECONDS)
           ' /tmp/skaffold/skaffold.yaml
 
-        if [ -s resolved_registries.out ]; then
-          cat resolved_registries.out | while read chart_location
-          do
-            chart_location=oci://$(echo "$chart_location" | awk -F':' '{print $1}') # strip the tag
-            echo "Verifying chart location: $chart_location by running helm show"
-            if helm show chart "$chart_location" --version "$CHART_VERSION"; then
-              echo "Setting chart location to $chart_location"
-              export CHART_LOCATION="$chart_location"
-              echo 'success' > /tmp/_status
-              break
-            else
-              echo 'failed' > /tmp/_status
-              continue
-            fi
-          done
-          status=$(cat /tmp/_status)
-          if [ "$status" = 'success' ]; then
-            rm resolved_registries.out /tmp/_status
-          else
-            echo "Failed to resolve any of the provided registry mirrors"
-            rm resolved_registries.out /tmp/_status
+        if [ -s "${resolved_registries}" ]; then
+          findChartInMirrors() {
+            cat ${resolved_registries} | while read chart_location
+            do
+              chart_location=oci://$(echo "$chart_location" | awk -F':' '{print $1}') # strip the tag
+              echo "Verifying chart location: $chart_location by running helm show"
+              if helm show chart "$chart_location" --version "$CHART_VERSION"; then
+                echo "Setting chart location to $chart_location"
+                export CHART_LOCATION="$chart_location"
+                exit 0
+              fi
+            done
+
+            echo "Failed to find chart in any of the configured registry mirrors" >&2
             exit 1
-          fi
+          }
+
+          findChartInMirrors
         fi
 
         if echo "$CHART_LOCATION" | grep -q '^oci://'; then # remote chart
